export const CRIME_TYPES = {
  FINANCIAL_FRAUD: 'financial_fraud',
  UPI_FRAUD: 'upi_fraud',
  CARD_FRAUD: 'card_fraud',
  PHISHING: 'phishing',
  IDENTITY_THEFT: 'identity_theft',
  SOCIAL_MEDIA_HACK: 'social_media_hack',
  FAKE_PROFILE: 'fake_profile',
  CYBERBULLYING: 'cyberbullying',
  HARASSMENT: 'harassment',
  SEXTORTION: 'sextortion',
  RANSOMWARE: 'ransomware',
  MALWARE: 'malware',
  OTP_SCAM: 'otp_scam',
  SIM_SWAP: 'sim_swap',
  KYC_FRAUD: 'kyc_fraud',
  LOAN_APP_THREAT: 'loan_app_threat',
  JOB_SCAM: 'job_scam',
  IMPERSONATION: 'impersonation',
  CRYPTO_FRAUD: 'crypto_fraud',
  OTHER: 'other',
} as const

export type CrimeType = typeof CRIME_TYPES[keyof typeof CRIME_TYPES]

export const CRIME_TYPE_LABELS: Record<CrimeType, string> = {
  [CRIME_TYPES.FINANCIAL_FRAUD]: 'Financial Fraud',
  [CRIME_TYPES.UPI_FRAUD]: 'UPI Fraud',
  [CRIME_TYPES.CARD_FRAUD]: 'Card Fraud',
  [CRIME_TYPES.PHISHING]: 'Phishing',
  [CRIME_TYPES.IDENTITY_THEFT]: 'Identity Theft',
  [CRIME_TYPES.SOCIAL_MEDIA_HACK]: 'Social Media Hack',
  [CRIME_TYPES.FAKE_PROFILE]: 'Fake Profile',
  [CRIME_TYPES.CYBERBULLYING]: 'Cyberbullying',
  [CRIME_TYPES.HARASSMENT]: 'Harassment',
  [CRIME_TYPES.SEXTORTION]: 'Sextortion',
  [CRIME_TYPES.RANSOMWARE]: 'Ransomware',
  [CRIME_TYPES.MALWARE]: 'Malware',
  [CRIME_TYPES.OTP_SCAM]: 'OTP Scam',
  [CRIME_TYPES.SIM_SWAP]: 'SIM Swap',
  [CRIME_TYPES.KYC_FRAUD]: 'KYC Fraud',
  [CRIME_TYPES.LOAN_APP_THREAT]: 'Loan App Threat',
  [CRIME_TYPES.JOB_SCAM]: 'Job Scam',
  [CRIME_TYPES.IMPERSONATION]: 'Impersonation',
  [CRIME_TYPES.CRYPTO_FRAUD]: 'Crypto Fraud',
  [CRIME_TYPES.OTHER]: 'Other',
}
